.github/workflows/pythonpackage.yml
README.md
dcm_spec_tools/spec_reader/tests/test_edition_reader.py
dcm_spec_tools/validate_iods.py
setup.py

- mrbean-bremen/dcm-spec-tools is now pydicom/dicom-validator

Adapt documentation after renaming/moving repository

---

dicom_validator/spec_reader/edition_reader.py
dicom_validator/spec_reader/part3_reader.py
dicom_validator/spec_reader/tests/test_spec_reader.py
dicom_validator/validate_iods.py
dicom_validator/validator/dicom_file_validator.py
dicom_validator/validator/iod_validator.py

This PR:
- Fixes broken module_info.json: The indented attributes were not handled correctly. Different indent levels got mixed together.
- Fixes duplicate logger output (`logger.hasHandlers()` vs `logger.handlers`)
- Adds --force-read command line option to validate_iods.py (for validating DCM files without DICOM header)
- Traverses the entire DICOM dataset, not just the module's top-level.
- Checks for "unexpected" attributes: Some attributes are either non-standard or they exist in the wrong place in the dataset. This check warns/errors about these cases.

Validate entire dataset

---

.github/workflows/pythonpackage.yml
CHANGES.md
dicom_validator/spec_reader/condition.py
dicom_validator/spec_reader/condition_parser.py
dicom_validator/spec_reader/tests/test_condition_parser.py
setup.py

- crashed due to mishandled condition without values
- fixes #15
- remove CI build for EOL Python 3.6 (no more available)

Fix crash on loading DICOM specs 2022b

---

CHANGES.md
dicom_validator/spec_reader/condition.py
dicom_validator/spec_reader/condition_parser.py
dicom_validator/spec_reader/tests/test_condition_parser.py
dicom_validator/tests/fixtures/2021d/json/dict_info.json

- if the values for a condition needing a value cannot be parsed, the condition is now ignored
- fixes #20
- add handling of a few more simple conditions

Fix handling of missing values

---

dicom_validator/tests/spec_reader/test_condition.py
dicom_validator/tests/spec_reader/test_condition_parser.py
dicom_validator/tests/spec_reader/test_part4_reader.py
dicom_validator/tests/validator/test_dicom_file_validator.py
dicom_validator/tests/validator/test_iod_validator.py

- many tests have been disabled accidentally after moving them to pytest
- use correct order in assertions
- avoid deprecation warning from pydicom
(noticed this while adding new tests)

Rename test classes to be found by pytest

---

CHANGES.md
TODO.md
dicom_validator/spec_reader/part3_reader.py
dicom_validator/tests/conftest.py
dicom_validator/tests/fixtures/2021d/docbook/part03.xml
dicom_validator/tests/fixtures/2021d/json/iod_info.json
dicom_validator/tests/fixtures/2021d/json/module_info.json
dicom_validator/tests/spec_reader/test_part3_reader.py
dicom_validator/tests/spec_reader/test_part6_reader.py
dicom_validator/tests/utils.py
dicom_validator/tests/validator/test_iod_validator.py
dicom_validator/tests/validator/test_iod_validator_func_groups.py
dicom_validator/validator/iod_validator.py

- add functional group macro info to iod info
- add special handling for functional groups
- still missing: handle macros that are not allowed in either shared or per-frame groups handle duplicate tags in both groups
This is ongoing work, but I'll probably merge an initial version first, and handle other problems first before going back to this.

Add initial support for handling functional groups

---

.github/workflows/testsuite.yml
CHANGES.md
dicom_validator/spec_reader/condition_parser.py
dicom_validator/tests/spec_reader/test_condition_parser.py
dicom_validator/tests/validator/test_iod_validator_func_groups.py

- caused false positives
- fixes #32

Fix handling of unverifiable and condition

---

CHANGES.md
TODO.md
dicom_validator/spec_reader/condition.py
dicom_validator/spec_reader/condition_parser.py
dicom_validator/spec_reader/part3_reader.py
dicom_validator/tests/fixtures/2021d/json/iod_info.json
dicom_validator/tests/fixtures/2021d/json/module_info.json
dicom_validator/tests/spec_reader/test_condition_parser.py
dicom_validator/tests/spec_reader/test_part3_reader.py
dicom_validator/tests/validator/test_iod_validator_func_groups.py
dicom_validator/validator/iod_validator.py

- add checks for macros that are not allowed in shared or per-frame functional groups
- add check that macros are not present in both shared and per-frame functional groups
- closes #27

Add more support for functional groups

---

CHANGES.md
README.md
dicom_validator/spec_reader/part3_reader.py
dicom_validator/tests/fixtures/2021d/docbook/part03.xml
dicom_validator/tests/fixtures/2021d/json/iod_info.json
dicom_validator/tests/fixtures/2021d/json/module_info.json
dicom_validator/tests/spec_reader/test_part3_reader.py
dicom_validator/tests/validator/test_iod_validator.py
dicom_validator/validator/iod_validator.py

- needed for validation of SR Document Content
- closes #39

Add handling of conditional includes

---

.github/workflows/get_revision.py
CHANGES.md
README.md
TODO.md
dicom_validator/spec_reader/condition.py
dicom_validator/spec_reader/condition_parser.py
dicom_validator/tests/spec_reader/test_condition_parser.py
dicom_validator/tests/test_cmdline_tools.py
dicom_validator/tests/validator/test_iod_validator.py

* correctly parse the value index for some expressions
* make the parsing stricter to avoid false positives
* fix parsing of conditions for AT values with equality comparison (fixes #58)

Fix some issues in the condition parser

---

.gitignore
CHANGES.md
README.md
TODO.md
dicom_validator/spec_reader/enum_parser.py
dicom_validator/spec_reader/part3_reader.py
dicom_validator/spec_reader/part4_reader.py
dicom_validator/spec_reader/part6_reader.py
dicom_validator/spec_reader/spec_reader.py
dicom_validator/tests/spec_reader/test_enum_parser.py
dicom_validator/tests/spec_reader/test_part3_reader.py
dicom_validator/tests/utils.py
dicom_validator/tests/validator/test_iod_validator.py
dicom_validator/validator/iod_validator.py

- directly mentioned and linked enumerated values are handled, 
some indirectly defined values are not handled yet
- see #54 
Still to do:
- values depending on a condition
- single values not defined in an enumeration ("value shall be...")
- probably more...

Add validation of enumerated values

---

CHANGES.md
dicom_validator/dump_dcm_info.py
dicom_validator/spec_reader/enum_parser.py
dicom_validator/spec_reader/part3_reader.py
dicom_validator/tests/test_cmdline_tools.py

- this was a regression due to incomplete refactoring
Also fixed a deprecation warning.

Fix crash of the dump tool

---

.github/workflows/testsuite.yml
CHANGES.md
dicom_validator/spec_reader/part3_reader.py
dicom_validator/tests/spec_reader/conftest.py
dicom_validator/tests/spec_reader/test_part3_reader.py
dicom_validator/tests/test_cmdline_tools.py
requirements-dev.txt

- this happened at least for revisions from 2015 to 2019
- add some parsing tests for older revision

Fixed exception on parsing some older DICOM standard versions

---

CHANGES.md
README.md
dicom_validator/spec_reader/edition_reader.py
dicom_validator/spec_reader/enum_parser.py
dicom_validator/tests/spec_reader/conftest.py
dicom_validator/tests/spec_reader/test_edition_reader.py
dicom_validator/tests/spec_reader/test_enum_parser.py
dicom_validator/tests/spec_reader/test_part3_reader.py
dicom_validator/tests/test_cmdline_tools.py
dicom_validator/tests/validator/conftest.py
dicom_validator/tests/validator/test_iod_validator.py
dicom_validator/validator/iod_validator.py

- fix checking of multi-valued tags with defined enum values
- fixes #87

Add check of enum values defined for a specific index

---

CHANGES.md
dicom_validator/tests/validator/test_dicom_file_validator.py
dicom_validator/tests/validator/test_iod_validator.py
dicom_validator/validate_iods.py
dicom_validator/validator/dicom_file_validator.py
dicom_validator/validator/iod_validator.py

Fix for #102
- Added check for value representation by calling pydicom's `validate_value` directly
- Suppressed warnings about invalid values while reading DICOM file
- Added option to suppress this new check
- Updated unit test, since user warning is no longer issued for invalid SOPClassUID. A fatal error is raised correctly.

Validate values against value representations

---

CHANGES.md
dicom_validator/dump_dcm_info.py
dicom_validator/validate_iods.py
dicom_validator/validator/dicom_file_validator.py

Fix for issue #105 
- Suppressed pydicom's warnings coming from `dcmread`
- Replaced `exit` with `sys.exit`, since the primary usage is within a program (Reference: [stackoverflow](https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python))
- Updated `changes.md` with correct version number

Suppress warnings from dump_dcm_info

---

CHANGES.md
README.md
_typos.toml
dicom-validator.spec
requirements-dev.txt

Fix for issue #104
- Added pyinstaller dependency for development
- Added spec file for `pyinstaller` to build executables
- Added instructions in README.md
- Updated change log

Build executables using pyinstaller on Windows

---

.github/workflows/build_windows_exe.yml
.github/workflows/release-deploy.yml

- Added a new workflow to build executables on Windows when a pull request is opened
- For windows only, added steps to build and deploy windows executables to GitHub release.
- If this PR looks good, it can replace PR #108.

Release windows executable as part of release-deploy

---

CHANGES.md
dicom_validator/spec_reader/part3_reader.py
dicom_validator/tests/spec_reader/test_condition_parser.py
dicom_validator/tests/spec_reader/test_part3_reader.py

Fix `Graphic Filled (0070,0024)` validation condition

---

CHANGES.md
dicom_validator/spec_reader/condition_parser.py
dicom_validator/spec_reader/part3_reader.py
dicom_validator/tests/spec_reader/test_condition_parser.py
dicom_validator/tests/spec_reader/test_part3_reader.py
dicom_validator/tests/validator/test_iod_validator.py
dicom_validator/tests/validator/test_iod_validator_func_groups.py
dicom_validator/validator/iod_validator.py

- handle ", that is" phrase
- handle mixed ORed values and conditions
- catch incorrectly parsed value type
- remove now unneeded special case
@drahoja9 - please have a look. I reverted some of your changes, as the special handling is no longer needed, but let the mechanism in place.

Partly fix parsing of Graphic Annotation condition

---

CHANGES.md
dicom_validator/spec_reader/condition_parser.py
dicom_validator/tests/spec_reader/test_condition_parser.py

- prevents an exception during parsing
- the root cause is a problem with the parser which creates incorrect output, the reason is still unknown
- fixes #119

Add missing bounds check

---

CHANGES.md
README.md
dicom_validator/tests/validator/test_dicom_file_validator.py
pyproject.toml

- makes it compatible to pydicom 3
- also promote to beta state

Replace removed pydicom API

---

.github/workflows/testsuite.yml
CHANGES.md
pyproject.toml

- exclude macOS due to an issue in pyfakefs

Add CI tests for Python 3.13

---

CHANGES.md
dicom_validator/spec_reader/part3_reader.py
dicom_validator/tests/spec_reader/test_part3_reader.py
dicom_validator/tests/validator/test_iod_validator_func_groups.py
dicom_validator/validator/iod_validator.py

- several newer IODs are in sub-chapters (like A.86.1.15)
- 2 group macro definitions are at a level below the usual one
- fixes #193

Find deeper nested IODs and group macros

---

dicom_validator/spec_reader/condition.py
dicom_validator/tag_tools.py
dicom_validator/tests/validator/test_iod_validator_func_groups.py
dicom_validator/validator/error_handler.py
dicom_validator/validator/iod_validator.py
dicom_validator/validator/validation_result.py

- this is derived from int and has already the needed convenience
- adapt error handling to group tags inside the same sequence
- add more typing
See #205, ongoing work.

Use BaseTag instead of int for tags
